services:
  timescale:
    image: timescale/timescaledb:2.18.0-pg17
    restart: always
    container_name: postgres
    ports:
      - '5432:5432'
    volumes:
      - 'postgres-data:/pgdata'
    env_file: .env.infra

  rabbitmq:
    image: rabbitmq:4.2.2-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - 'rabbit-data:/var/lib/rabbitmq'
    env_file: .env.infra

volumes:
  postgres-data:
  rabbit-data:
