name: Build & Push Quarkus Native Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'openjdk'
          java-version: 21.0.2
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Build with Gradle
        run: ./gradlew buildNative

      # 2) Log in to a container registry
      #    (example here is GitHub Container Registry)
      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3) Set up Buildx (recommended for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4) Build & Push the Docker image
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: src/main/docker/Dockerfile.native   # <â€” your Quarkus native Dockerfile
          push: true                                # push to registry
          tags: ${{ vars.DOCKERHUB_USERNAME }}/emaildemo:latest
          # (optional) add platforms if you need multi-arch builds:
          # platforms: linux/amd64,linux/arm64
